# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'socket_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/sophyda/.designer/backup/hzau_logo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 430, 400))
        self.label.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 100, 430, 400))
        self.label_2.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 60, 161, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 70, 141, 21))
        self.label_4.setObjectName("label_4")
        self.webwidget = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webwidget.setGeometry(QtCore.QRect(1340, 100, 430, 400))
        self.webwidget.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.webwidget.setObjectName("webwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1790, 660, 121, 81))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1820, 620, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1811, 130, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1811, 270, 81, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1780, 160, 101, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(1780, 300, 101, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1350, 570, 191, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid #3C3C3C!important;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1350, 730, 191, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1540, 70, 72, 15))
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1350, 650, 91, 61))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(1509, 820, 251, 51))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(1510, 880, 251, 51))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1378, 840, 81, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1360, 900, 131, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(1830, 780, 51, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(1830, 850, 51, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1830, 760, 72, 15))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1831, 820, 71, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1690, 570, 81, 61))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1590, 570, 81, 61))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1590, 640, 81, 31))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1590, 680, 81, 31))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1831, 900, 71, 21))
        self.label_16.setObjectName("label_16")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(1830, 930, 51, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1820, 980, 72, 15))
        self.label_17.setObjectName("label_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(1830, 1000, 51, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1450, 650, 91, 61))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1371, 960, 91, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(1510, 940, 251, 51))
        self.lineEdit_5.setStyleSheet("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1800, 530, 101, 31))
        self.label_19.setStyleSheet("font: 15pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(650, 10, 471, 31))
        self.label_20.setStyleSheet("font: 25pt \"隶书\";")
        self.label_20.setObjectName("label_20")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1060, 70, 141, 21))
        self.label_10.setObjectName("label_10")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1350, 1010, 151, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(1510, 1000, 251, 51))
        self.lineEdit_10.setStyleSheet("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1590, 730, 181, 61))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(900, 100, 430, 400))
        self.label_26.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1690, 640, 81, 71))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background:#647687;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:12pt;border-radius: 10px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(30, 10, 81, 81))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("C:/Users/sophyda/.designer/backup/hzau_logo1.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(640, 1010, 421, 31))
        self.label_29.setObjectName("label_29")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1060, 1000, 51, 41))
        self.label_27.setStyleSheet("")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("C:/Users/sophyda/.designer/backup/robot.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1340, 520, 441, 291))
        self.label_30.setStyleSheet("QLabel{border:2px solid #242424;border-radius:25px}")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1510, 530, 101, 31))
        self.label_31.setStyleSheet("font: 15pt \"微软雅黑\";\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 570, 430, 400))
        self.label_9.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(180, 540, 91, 20))
        self.label_18.setObjectName("label_18")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(900, 570, 430, 400))
        self.label_24.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(460, 570, 430, 400))
        self.label_22.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(1070, 540, 121, 20))
        self.label_25.setObjectName("label_25")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(630, 540, 91, 20))
        self.label_23.setObjectName("label_23")
        self.label_30.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.webwidget.raise_()
        self.lcdNumber.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.label_16.raise_()
        self.lineEdit_8.raise_()
        self.label_17.raise_()
        self.lineEdit_9.raise_()
        self.pushButton_10.raise_()
        self.label_13.raise_()
        self.lineEdit_5.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_10.raise_()
        self.label_21.raise_()
        self.lineEdit_10.raise_()
        self.pushButton_5.raise_()
        self.label_26.raise_()
        self.pushButton_11.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_27.raise_()
        self.label_31.raise_()
        self.label_9.raise_()
        self.label_18.raise_()
        self.label_24.raise_()
        self.label_22.raise_()
        self.label_25.raise_()
        self.label_23.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 33))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "温室巡检机器人监控软件"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "前方摄像头视角"))
        self.label_4.setText(_translate("MainWindow", "realsense 视角"))
        self.label_5.setText(_translate("MainWindow", "温度"))
        self.label_6.setText(_translate("MainWindow", "经度"))
        self.label_7.setText(_translate("MainWindow", "纬度"))
        self.pushButton_2.setText(_translate("MainWindow", "启动服务"))
        self.pushButton_3.setText(_translate("MainWindow", "开始测量"))
        self.label_8.setText(_translate("MainWindow", "GPS"))
        self.pushButton_4.setText(_translate("MainWindow", "标记"))
        self.label_11.setText(_translate("MainWindow", "叶片数："))
        self.label_12.setText(_translate("MainWindow", "总面积cm^2："))
        self.label_14.setText(_translate("MainWindow", "CO2"))
        self.label_15.setText(_translate("MainWindow", "光照"))
        self.pushButton_6.setText(_translate("MainWindow", "停止"))
        self.pushButton_7.setText(_translate("MainWindow", "启动"))
        self.pushButton_8.setText(_translate("MainWindow", "上偏"))
        self.pushButton_9.setText(_translate("MainWindow", "下偏"))
        self.label_16.setText(_translate("MainWindow", "湿度"))
        self.label_17.setText(_translate("MainWindow", "TVOC"))
        self.pushButton_10.setText(_translate("MainWindow", "拍照"))
        self.label_13.setText(_translate("MainWindow", "株高mm："))
        self.label_19.setText(_translate("MainWindow", "环境信息"))
        self.label_20.setText(_translate("MainWindow", "温室巡检机器人监控软件"))
        self.label_10.setText(_translate("MainWindow", "深度图"))
        self.label_21.setText(_translate("MainWindow", "平均面积cm^2："))
        self.pushButton_5.setText(_translate("MainWindow", "测量结果"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_11.setText(_translate("MainWindow", "调转"))
        self.label_29.setText(_translate("MainWindow", "Powered By HZAU-Agriculture Robot Lab"))
        self.label_31.setText(_translate("MainWindow", "控制中心"))
        self.label_18.setText(_translate("MainWindow", "拍摄图片"))
        self.label_25.setText(_translate("MainWindow", "生长点检测"))
        self.label_23.setText(_translate("MainWindow", "叶片分割"))
from PyQt5 import QtWebEngineWidgets
